#[target.x86_64-unknown-linux-gnu]
#rustflags = [
#    "-C", "link-arg=-fuse-ld=mold",
#]

[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "target-feature=+crt-static"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.stable-aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
